# 🤖 Dependabot Configuration for Automated Dependency Updates
# This file configures Dependabot to automatically create pull requests for dependency updates

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "CrzyHAX91"
    assignees:
      - "CrzyHAX91"
    labels:
      - "dependencies"
      - "python"
      - "security"
    commit-message:
      prefix: "🔒 SECURITY"
      prefix-development: "🔧 DEV"
      include: "scope"
    # Security updates get priority
    allow:
      - dependency-type: "all"
    # Group security updates together
    groups:
      security-updates:
        patterns:
          - "flask*"
          - "tornado*"
          - "werkzeug*"
          - "setuptools*"
          - "requests*"
          - "urllib3*"
          - "cryptography*"
          - "django*"
          - "h11*"
        update-types:
          - "security"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:30"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "CrzyHAX91"
    assignees:
      - "CrzyHAX91"
    labels:
      - "dependencies"
      - "javascript"
      - "security"
    commit-message:
      prefix: "🔒 SECURITY"
      prefix-development: "🔧 DEV"
      include: "scope"
    allow:
      - dependency-type: "all"
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
      development-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "CrzyHAX91"
    assignees:
      - "CrzyHAX91"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
    commit-message:
      prefix: "🔧 CI/CD"
      include: "scope"
    allow:
      - dependency-type: "all"

  # Docker dependencies (if applicable)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "CrzyHAX91"
    assignees:
      - "CrzyHAX91"
    labels:
      - "dependencies"
      - "docker"
      - "infrastructure"
    commit-message:
      prefix: "🐳 DOCKER"
      include: "scope"
    allow:
      - dependency-type: "all"
