version: 2
updates:
  # Enable version updates for npm (main project)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "CrzyHAX91"
    assignees:
      - "CrzyHAX91"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Security-focused updates
    allow:
      - dependency-type: "all"
    # Auto-merge patch-level security updates
    groups:
      security-patches:
        patterns:
          - "*"
        update-types:
          - "patch"

  # Enable version updates for npm (baddbeatz)
  - package-ecosystem: "npm"
    directory: "/baddbeatz"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:15"
    open-pull-requests-limit: 5
    reviewers:
      - "CrzyHAX91"
    assignees:
      - "CrzyHAX91"
    commit-message:
      prefix: "deps(baddbeatz)"
      prefix-development: "deps-dev(baddbeatz)"
      include: "scope"
    labels:
      - "dependencies"
      - "baddbeatz"
      - "automated"
    allow:
      - dependency-type: "all"
    groups:
      security-patches:
        patterns:
          - "*"
        update-types:
          - "patch"

  # Enable version updates for npm (backend)
  - package-ecosystem: "npm"
    directory: "/baddbeatz/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
    open-pull-requests-limit: 3
    reviewers:
      - "CrzyHAX91"
    assignees:
      - "CrzyHAX91"
    commit-message:
      prefix: "deps(backend)"
      prefix-development: "deps-dev(backend)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "automated"
    allow:
      - dependency-type: "all"
    groups:
      security-patches:
        patterns:
          - "*"
        update-types:
          - "patch"

  # Enable version updates for npm (streaming-app)
  - package-ecosystem: "npm"
    directory: "/baddbeatz/streaming-app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:45"
    open-pull-requests-limit: 3
    reviewers:
      - "CrzyHAX91"
    assignees:
      - "CrzyHAX91"
    commit-message:
      prefix: "deps(streaming)"
      prefix-development: "deps-dev(streaming)"
      include: "scope"
    labels:
      - "dependencies"
      - "streaming"
      - "automated"
    allow:
      - dependency-type: "all"
    groups:
      security-patches:
        patterns:
          - "*"
        update-types:
          - "patch"

  # Enable version updates for pip (Python dependencies)
  - package-ecosystem: "pip"
    directory: "/baddbeatz"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "CrzyHAX91"
    assignees:
      - "CrzyHAX91"
    commit-message:
      prefix: "deps(python)"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "automated"
    allow:
      - dependency-type: "all"
    # Ignore known problematic packages until manually fixed
    ignore:
      - dependency-name: "pydantic"
        versions: [">2.10.0"]
      - dependency-name: "rich"
        versions: [">=14.0.0"]
      - dependency-name: "click"
        versions: [">=8.2.0"]
      - dependency-name: "cachetools"
        versions: [">=6.0.0"]
    groups:
      security-patches:
        patterns:
          - "*"
        update-types:
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
    open-pull-requests-limit: 3
    reviewers:
      - "CrzyHAX91"
    assignees:
      - "CrzyHAX91"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci/cd"
      - "automated"
    allow:
      - dependency-type: "all"
    groups:
      security-patches:
        patterns:
          - "*"
        update-types:
          - "patch"

  # Security-only updates (daily for critical vulnerabilities)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "CrzyHAX91"
    assignees:
      - "CrzyHAX91"
    commit-message:
      prefix: "security"
      include: "scope"
    labels:
      - "security"
      - "critical"
      - "automated"
    allow:
      - dependency-type: "direct"
        update-types: ["security"]
      - dependency-type: "indirect"
        update-types: ["security"]

  # Security-only updates for Python (daily)
  - package-ecosystem: "pip"
    directory: "/baddbeatz"
    schedule:
      interval: "daily"
      time: "06:15"
    open-pull-requests-limit: 10
    reviewers:
      - "CrzyHAX91"
    assignees:
      - "CrzyHAX91"
    commit-message:
      prefix: "security(python)"
      include: "scope"
    labels:
      - "security"
      - "python"
      - "critical"
      - "automated"
    allow:
      - dependency-type: "direct"
        update-types: ["security"]
      - dependency-type: "indirect"
        update-types: ["security"]
