# LiteLLM Configuration for Context Window Management
# This configuration addresses the context window exceeded error

model_list:
  # Primary models with context window limits
  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      max_tokens: 1047576
      context_window: 1047576
    model_info:
      mode: chat
      supports_function_calling: true
      supports_vision: true

  # Fallback models for context window exceeded scenarios
  - model_name: gpt-4-turbo
    litellm_params:
      model: gpt-4-turbo
      max_tokens: 4096000
      context_window: 4096000
    model_info:
      mode: chat
      supports_function_calling: true
      supports_vision: true

  - model_name: claude-3-sonnet
    litellm_params:
      model: anthropic/claude-3-sonnet-20240229
      max_tokens: 200000
      context_window: 200000
    model_info:
      mode: chat
      supports_function_calling: true

  - model_name: qwen-72b
    litellm_params:
      model: Qwen/Qwen2.5-72B-Instruct-Turbo
      max_tokens: 32768
      context_window: 32768
    model_info:
      mode: chat

  - model_name: deepseek-chat
    litellm_params:
      model: deepseek/deepseek-chat
      max_tokens: 32768
      context_window: 32768
    model_info:
      mode: chat

# Router configuration with fallbacks
router_settings:
  routing_strategy: "usage-based-routing-v2"
  model_group_alias:
    gpt-4o-mini: ["gpt-4o-mini"]
    gpt-4-turbo: ["gpt-4-turbo"]
    claude-sonnet: ["claude-3-sonnet"]
    qwen-turbo: ["qwen-72b"]
    deepseek: ["deepseek-chat"]

  # Context window fallback configuration
  context_window_fallbacks:
    - gpt-4o-mini:
        - gpt-4-turbo
        - claude-3-sonnet
        - qwen-72b
        - deepseek-chat
    - gpt-4-turbo:
        - claude-3-sonnet
        - qwen-72b
    - claude-3-sonnet:
        - qwen-72b
        - deepseek-chat

  # Fallback configuration for different scenarios
  fallbacks:
    - Qwen/Qwen2.5-72B-Instruct-Turbo: ["gpt-4-turbo"]
    - custom/blackbox-pro: ["anthropic/claude-3-sonnet-20240229"]
    - deepseek/deepseek-chat: ["gpt-4-turbo"]
    - gpt-4o-mini: ["gpt-4-turbo", "anthropic/claude-3-sonnet-20240229", "Qwen/Qwen2.5-72B-Instruct-Turbo"]

# General settings
general_settings:
  master_key: "your-master-key-here"
  database_url: "your-database-url-here"
  
  # Context management settings
  max_context_window_policy: "truncate_oldest"
  context_window_buffer: 1000  # Reserve tokens for response
  
  # Retry and timeout settings
  num_retries: 3
  request_timeout: 600
  
  # Logging
  set_verbose: true
  json_logs: true

# Cost and performance optimization
cost_tracking:
  track_cost_per_model: true
  budget_manager: true

# Health checks and monitoring
health_check:
  healthy_endpoints: true
  unhealthy_endpoints: false
