# wrangler.toml
name = "baddbeatzv1"
compatibility_date = "2025-05-21"
main = "workers-site/index.js"
type = "webpack"
workers_dev = true

[site]
bucket = "./"
routes = [
  { pattern = "www.baddbeatz.nl", custom_domain = true }
]
