# wrangler.toml
name = "baddbeatzv1"
compatibility_date = "2025-05-21"
main = "workers-site/index.js"

[site]
bucket = "./"
routes = [
  { pattern = "www.baddbeatz.nl", custom_domain = true }
]


[vars]
# Provide your OpenAI API key via `wrangler secret put OPENAI_API_KEY`
# or by setting the variable in the Cloudflare dashboard. The value is
# intentionally omitted here so it isn't committed to version control.

[observability.logs]
enabled = true
