name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci

      # Check for requirements-dev.txt before running Python steps
      - name: Check for requirements-dev.txt
        id: requirements-dev
        run: echo "exists=$(if [ -f requirements-dev.txt ]; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT
        working-directory: ${{ github.workspace }}
      - uses: actions/setup-python@v4
        if: steps.requirements-dev.outputs.exists == 'true'
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: requirements-dev.txt
      - run: pip install -r requirements-dev.txt
        if: steps.requirements-dev.outputs.exists == 'true'
        working-directory: ${{ github.workspace }}

      - run: pip install requests_mock
        if: steps.requirements-dev.outputs.exists == 'true'

      - run: npm run build-docs

      - run: npm test

      - run: pytest -q
        if: steps.requirements-dev.outputs.exists == 'true'
