name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Documentation
        run: npm run build-docs

      - name: Configure Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: ''

      - name: Upload Documentation
        uses: actions/upload-artifact@v3
        with:
          path: './docs'

      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

